# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 185b7f5db5be721f8388b57699483a9b02d92f2628be7360bc5548c23ed85232bbdebe2b275cf01a8e2fa18ea48d52ce2ef9ff3ddc4ea31072f93f789bd25867

test:
  secret_key_base: 70ac640c8086e71778644fecac8051b6906c5ea4819795efcf1071a15a23375b0ddd130e31c6675ad3649fc579f97e3cc05f241bdf560717f7632adb80cec77c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
